[package]
name = "combine_line"
version = "0.1.0"
authors = ["Taekyun Kim <taekyunk@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
regex = "1.5.5"
lazy_static = "1.2.0"
itertools = "0.8.0" 
thread_local = "1.1.4"

